[gcp_service_account]
type= "service_account"
project_id= "flyer-tracker-486422"
private_key_id= "87c8785b7df22180f05795c8f3d01797eacc74d7"
private_key= """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4inzv2NQOoH4j
s+tWePJCJhHmhF89u66U7Thw1sHHoS7tA3dGErQudpg8k1XarRXUxmhPFuVUMrR8
q030zXw9U1SAyavBtK2JkeXBY7pcMAHxYi7HXg+fIGzDA6sdE2U5P01crDLSSyqk
p2uXkbwPeF/pgRdjQkVhXrKri8yPG/BxQpo4WtLnUEokjLsr5XTsWTcRFBbI1qdp
9F7HStRCC3RzqdJ91fpSuutKuGWVj4LijZ4Iuz0IXBPyfR4IVQwxQxnWPFEQ7Aj0
gPR3rfMJGh7Tue2akCE2I1ms3S1Jg3F651ITnsNfnDAJk7OJWuffM74PPXW6H7oJ
rMfBITE/AgMBAAECggEACbTwBaYh/OxOq5VtRMlBZdCs0s/PAVkNlwleasHtisnV
xUblgVH3pr/Ji74lkPDzxnbWH1A04lCRzEK9JKoTrMk6UBxZwQfatA+pjWFahx4t
HcOeOZ/0axFV46nlLbcgA14VmN9OWQqEPdC4LGrtAKn7RDXP/FebC1EcaeuTkthK
1PUQwFuFzMFvgGZQKg1Br6t3PGSNdmfmPtuw7SlKsmLtlW5OsP/fddn0j4HP5hNU
gUZQEs9YyGXzyDMWGYrcblp2NbDkIfMh6CBESm9/fJNjATDBl2AxcGdbtFUakjWf
uNReth1meUFMUzIA5l0x44EwD5gUOpWxfBj4ZTNcIQKBgQDgofVcQskaK3jJ31Eh
N5PCpq4zDxSbEP2tvUJjbg97EyNjM9sT+EyXjmC7U5agQPjpYTxZBkeF9Bvd7QWg
45eQNC19J3rGLhpPPnrgcRVoU2cWPtL8JJtLQSo8cKAqStrRilV2gzY+nk8MATLZ
poy8ase+OSSmjxpD53kJ2Nq/LwKBgQDST1rP/or8KxpTnifQWoO8YrW/3rKZYHaH
YsRudVx2rEPZm6ud/P/7cEXGmg2XOtoFIgTaJyf0yRvAS6Nlqa56G51F3dCILMPj
5dYGKSbmpDlZHz8b9lTSWRYE5FE6AAnn3dlGU3rVkfrdNyoHqYiVVZ0aTnl+9NC6
01vuTCKq8QKBgB4Fp1xQVL5Zpwgb/6TX37i5PDj4wAFFkRICZHgTgqApW6ZrjNEr
c1kiH02KC2yZomrWoxEm5LJDgOH1RrZNFLmiL541g5QvHzcOG7AZjQnnc7Smat5m
Khcxu2pehxl/7aTpvyhauwo9cEUjd99dAhxAjTegPYTBRXpj2mp1gC7jAoGAUxgz
g1bJR1Uoc71bccExp69ArGyrGFq6ukdV4WbRf7oUnNga+LNL2ObFSvD3SbdhCQIl
9KPf76G+Kz43cyWV4H0kqMQ5bnRxeYwIAiskSaC9X+8umje7z9iPEKO9TDNTtp87
B8RYFiY1fk4bdyeO5aIMDqbO7lCAYDC+c+r1D6ECgYAEzi1O9mo/EHqHYlWmCRob
gGxGHM+joFxJv+FHUyoGGMVq+NgEXueNcAkbGt3N2xMge+IK3deOjtKIjVnNteyS
o4v6p33JZ+0Ddc11xcjCN2H0EaeMtdJ4RBuN4NQyhJrBdhoGee2lSobsCJMPM+zU
S6cVODgH0s380n2ue1kYzA==
-----END PRIVATE KEY-----
"""
client_email= "streamlit-bot@flyer-tracker-486422.iam.gserviceaccount.com"
client_id= "109128441936016193201"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot%40flyer-tracker-486422.iam.gserviceaccount.com"
universe_domain= "googleapis.com"